version: '3'
services:
  backend:
    build: ./RandomChatApp/backend
    ports:
      - "3000:3000"
    volumes:
      - ./RandomChatApp/backend/chat.db:/app/chat.db
  frontend:
    build: ./RandomChatApp/frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
